#!/usr/bin/env python3
import logging
from argparse import ArgumentParser
from sys import stdin
from pathlib import Path
import httpx


parser = ArgumentParser(description="Check URLs including follow_redirects.")
parser.add_argument(
    "-i",
    "--input_file",
    type=Path,
    required=False,
    help="Source: Inputfile with URLs to check. If no input file is given, read from stdin"
)
parser.add_argument(
    "-o",
    "--output_file",
    type=Path,
    required=False,
    help="Output: Outputfile to write checked URLs to, if no output file is given, write to stdout"
)

args = parser.parse_args()

if not args.input_file:
    urls = [line.strip() for line in stdin]
else:
    with open(args.input_file) as f:
        urls = [line.strip() for line in f]

if args.output_file:
    logging.basicConfig(filename=args.output_file, filemode="w", level=logging.INFO)
else:
    logging.basicConfig(level=logging.INFO)


with httpx.Client() as c:
    for url in urls:
        resp = c.get(url, follow_redirects=True)
